# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

# Create the Cranko release commit and build the engine JavaScript using
# ScriptSharp on Windows.

jobs:
- job: main
  pool:
    vmImage: windows-latest

  steps:

  - pwsh: |
      $d = Join-Path $Env:Temp cranko-$(New-Guid)
      [void][System.IO.Directory]::CreateDirectory($d)
      cd $d
      [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
      iex ((New-Object System.Net.WebClient).DownloadString('https://pkgw.github.io/cranko/fetch-latest.ps1'))
      echo "##vso[task.prependpath]$d"
    displayName: Install latest Cranko (Windows)

  - task: NodeTool@0
    displayName: Set up node.js
    inputs:
      versionSpec: '>=12'

  - bash: |
      set -xeuo pipefail
      git status # seems to help with mysterious Windows dirtiness issue
      cranko release-workflow apply-versions
      npm install # update package-lock.json
      git add .
      cranko release-workflow commit
      git show
    displayName: Generate release commit

  # Publish release commit as an artifact -- the next stages will need it.

  - pwsh: |
      mkdir $(Build.ArtifactStagingDirectory)\git-release
      git bundle create $(Build.ArtifactStagingDirectory)\git-release\release.bundle origin/master..HEAD
    displayName: Bundle release commit

  - task: PublishPipelineArtifact@1
    displayName: Publish git bundle artifact
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/git-release'
      artifactName: git-release

  # ScriptSharp build

  - task: MSBuild@1
    displayName: Build WebGL Engine with ScriptSharp
    inputs:
      solution: 'engine/WebGlEngine.sln'
      msbuildVersion: '16.0'
      msbuildArchitecture: 'x64'
      clean: true

  - task: CopyFiles@2
    displayName: Stage ScriptSharp artifacts
    inputs:
      sourceFolder: '.'
      contents: |
        engine/wwtlib/bin/wwtlib.js
      targetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true

  - task: PublishPipelineArtifact@0
    displayName: Publish ScriptSharp artifacts
    inputs:
      artifactName: scriptsharp
      targetPath: $(Build.ArtifactStagingDirectory)/engine/wwtlib/bin
